
spring:
  main:
    allow-bean-definition-overriding: true # boot 2.1 이후 빈 중복생성 막혔기 때문에 선언.
  jpa: # jpa
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl : true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql : true
        use_sql_comments : true
        format_sql : true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
  datasource: # postgresql
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/domiworld
    username: postgres
    password: 1715
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
      prefix : classpath:templates/
      suffix : .html
      cache : false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar

mybatis.type-aliases-package : com.domiworld
mybatis.mapper-locations : mybatis/mapper/**/*.xml   

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

